language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mkrzek15/docker-react-setup -f Dockerfile.dev .

script:
    - docker run -e CI=true mkrzek15/docker-react-setup npm run test
