language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mkrzek15/docker-react-setup -f Dockerfile.dev .

script:
    - docker run -e CI=true mkrzek15/docker-react-setup npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react-setup"
    env: "DockerReactSetup-env"
    bucket_name: "elasticbeanstalk-eu-west-2-016373601993"
    bucket_path: "docker-react-setup"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY